#kivy: 1.9.0


<Block>:
    size_hint: (None, None)
    size: (self.w, self.w)

    Label:
        canvas.before:
            Color:
                rgba: app.get_color_value(root.value)
            Rectangle:
                size: self.size
                pos: self.pos

        color: app.get_text_color(root.value)
        size_hint: (.9, .9)
        anchor_x: 'center'
        anchor_y: 'center'
        text: str(root.value)
        font_size: '36sp'
